-- AlterTable expenses
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "accountingCode" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "voucherNumber" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "invoiceNumber" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "vendorTaxId" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "isTaxInclusive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "transactionDate" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "payee" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;

-- AlterTable Ingredient
ALTER TABLE "Ingredient" ADD COLUMN IF NOT EXISTS "itemType" TEXT NOT NULL DEFAULT 'INGREDIENT';
